<?php

namespace Database\Seeders;

use App\Models\NewsArticle;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class ArticleTableSeeder extends Seeder
{
     /**
      * Run the database seeds.
      *
      * @return void
      */
     public function run()
     {
          $article1 = [
               'title' => 'Historique de la création de l\'institution',
               'resume' => 'Suite à l\'évaluation des activités de l\'Hôpital BETHESDA en 1993, il a été créé le département du Développement Communautaire et Assainissement du Milieu (D.C.A.M) afin d\'accompagner les activités de l\'hôpital par des actions de développement communautaire et de santé préventive.',
               'content' => "Suite à l'évaluation des activités de l'Hôpital BETHESDA en 1993, il a été créé le département du Développement Communautaire et Assainissement du Milieu (D.C.A.M) afin d'accompagner les activités de l'hôpital par des actions de développement communautaire et de santé préventive. Conformément à ses attributions en cette période, DCAM animait des formations sur la santé préventive au profit des femmes des églises et de la communauté de Sainte Rita, zone d'intervention de base de l'ONG BETHESDA qui a d'ailleurs été mise sur les fonts baptismaux le 19 février 1990. L'une de ces formations à laquelle les femmes de plusieurs églises avaient participée a porté sur la maladie du kwashiorkor qui est d'origine malnutritionnelle. A l'évaluation de la formation, une femme a été classée première avec une bonne moyenne démontrant ainsi sa maîtrise parfaite des causes de cette maladie de malnutrition.
            Quelques jours plus tard, le décès d'un des enfants de cette dame a suscité la visite des dirigeants de l'ONG BETHESDA chez elle pour une salutation fraternelle. Cette visite a permis aux autorités de l'ONG de constater que la dame vivait dans un environnement très insalubre et dans un habitat de taudis avec sa petite famille. Les symptômes du kwashiorkor étant manifestes sur les autres enfants, la délégation de BETHESDA a pu déduire de la nature de leur maladie grâce notamment, aux renseignements qu'ils ont eus sur la maladie dont l'enfant décédé avait souffert. Ménagère, son mari ne disposant pas d'un emploi, le foyer souffrait cruellement d'un manque de moyens financiers nécessaires pour s'assurer une alimentation équilibrée et de qualité.
            Très touché par ce constat, les dirigeants de DCAM et par ricochet, de l'ONG BETHESDA d'alors, ont compris que le développement intégral de l'homme ne s'arrête pas au traitement curatif et préventif de la maladie. Il faut le faire suivre d'une << guérison de la pauvreté>>. Pour avoir les moyens financiers nécessaires à la satisfaction des besoins vitaux de l'homme, il faut avoir un travail ; il faut exercer une activité génératrice de revenus. Après ces événements, en octobre 1995, DCAM a démarré les activités préparatoires d'appui aux activités génératrices de revenus (AGR). Le 20 avril 1996, cela a été institué et officiellement installé par le Conseil d'Administration (CA) de l'ONG BETHESDA. C'est alors la naissance de P.E.B.Co-BETHESDA. Ainsi, P.E.B.Co a connu une phase expérimentale sous forme de projet financé et géré entièrement par D.C.A.M jusqu'à la fin du mois de décembre 1999.
            Dans l'ensemble, les attentes escomptées par le Conseil d'Administration et la direction du D.C.A.M du projet ont été atteintes. Son impact sur la vie des populations de la commune de Sainte Rita, de Cotonou et de ses environs est certain. Les bienfaits et les réalisations du projet dans les communautés de l'Atlantique et du Littoral sont palpables de telle sorte qu'il a été souhaité de pérenniser l'action. Le programme, initialement appelé << Promotion d'Emploi et Banque Communautaire (P.E.B.Co)>> a donc été renforcé pour un meilleur impact. Cependant, sur recommandation des responsables de la Cellule de Micro finance, à cause du terme << banque >> P.E.B.Co est devenue Promotion d'Epargne/Crédit à Base Communautaire. Depuis la fin de l'exercice 2004, la Promotion d'Epargne/Crédit à Base Communautaire (P.E.B.Co) a été ôtée du Département Communautaire et Assainissement du Milieu (DCAM) et érigée en département de micro finance à part entière.
            Toujours dans le souci de se conformer aux réglementations en vigueur en ce qui concerne les systèmes financiers décentralisés, le Conseil d'Administration de l'ONG BETHESDA a concédé une autonomie de gestion à l'Association P.E.B.Co-BETHESDA en le dotant d'une direction générale hiérarchiquement dépendante du Conseil d'Administration de P.E.B.Co-BETHESDA et de nouveaux textes intitulés << Règlements et Statuts des Systèmes Financiers Décentralisés >>. L'Association P.E.B.Co-BETHESDA a en effet, acquis depuis son Assemblée Générale Constitutive du 11 mai 2013, son statut juridique à part entière, se conformant ainsi à la Nouvelle Loi N°2012-14 du 21 mars 2012 portant réglementation des Systèmes Financiers Décentralisés en République du Bénin. Elle n'est plus un département de l'ONG BETHESDA et est une structure totalement indépendante dans le fonctionnement comme dans l'organisation.",
               'location' => 'Cotonou',
               'image' => 'news_images/1KwlfUUcHhzHx6MzivnrUTvOhNtDUPUoBKqmVsZB.jpg'
          ];
          $article2 = [
               'title' => 'Historique de la création de l\'institution',
               'resume' => 'Suite à l\'évaluation des activités de l\'Hôpital BETHESDA en 1993, il a été créé le département du Développement Communautaire et Assainissement du Milieu (D.C.A.M) afin d\'accompagner les activités de l\'hôpital par des actions de développement communautaire et de santé préventive.',
               'content' => "Suite à l'évaluation des activités de l'Hôpital BETHESDA en 1993, il a été créé le département du Développement Communautaire et Assainissement du Milieu (D.C.A.M) afin d'accompagner les activités de l'hôpital par des actions de développement communautaire et de santé préventive. Conformément à ses attributions en cette période, DCAM animait des formations sur la santé préventive au profit des femmes des églises et de la communauté de Sainte Rita, zone d'intervention de base de l'ONG BETHESDA qui a d'ailleurs été mise sur les fonts baptismaux le 19 février 1990. L'une de ces formations à laquelle les femmes de plusieurs églises avaient participée a porté sur la maladie du kwashiorkor qui est d'origine malnutritionnelle. A l'évaluation de la formation, une femme a été classée première avec une bonne moyenne démontrant ainsi sa maîtrise parfaite des causes de cette maladie de malnutrition.
            Quelques jours plus tard, le décès d'un des enfants de cette dame a suscité la visite des dirigeants de l'ONG BETHESDA chez elle pour une salutation fraternelle. Cette visite a permis aux autorités de l'ONG de constater que la dame vivait dans un environnement très insalubre et dans un habitat de taudis avec sa petite famille. Les symptômes du kwashiorkor étant manifestes sur les autres enfants, la délégation de BETHESDA a pu déduire de la nature de leur maladie grâce notamment, aux renseignements qu'ils ont eus sur la maladie dont l'enfant décédé avait souffert. Ménagère, son mari ne disposant pas d'un emploi, le foyer souffrait cruellement d'un manque de moyens financiers nécessaires pour s'assurer une alimentation équilibrée et de qualité.
            Très touché par ce constat, les dirigeants de DCAM et par ricochet, de l'ONG BETHESDA d'alors, ont compris que le développement intégral de l'homme ne s'arrête pas au traitement curatif et préventif de la maladie. Il faut le faire suivre d'une << guérison de la pauvreté>>. Pour avoir les moyens financiers nécessaires à la satisfaction des besoins vitaux de l'homme, il faut avoir un travail ; il faut exercer une activité génératrice de revenus. Après ces événements, en octobre 1995, DCAM a démarré les activités préparatoires d'appui aux activités génératrices de revenus (AGR). Le 20 avril 1996, cela a été institué et officiellement installé par le Conseil d'Administration (CA) de l'ONG BETHESDA. C'est alors la naissance de P.E.B.Co-BETHESDA. Ainsi, P.E.B.Co a connu une phase expérimentale sous forme de projet financé et géré entièrement par D.C.A.M jusqu'à la fin du mois de décembre 1999.
            Dans l'ensemble, les attentes escomptées par le Conseil d'Administration et la direction du D.C.A.M du projet ont été atteintes. Son impact sur la vie des populations de la commune de Sainte Rita, de Cotonou et de ses environs est certain. Les bienfaits et les réalisations du projet dans les communautés de l'Atlantique et du Littoral sont palpables de telle sorte qu'il a été souhaité de pérenniser l'action. Le programme, initialement appelé << Promotion d'Emploi et Banque Communautaire (P.E.B.Co)>> a donc été renforcé pour un meilleur impact. Cependant, sur recommandation des responsables de la Cellule de Micro finance, à cause du terme << banque >> P.E.B.Co est devenue Promotion d'Epargne/Crédit à Base Communautaire. Depuis la fin de l'exercice 2004, la Promotion d'Epargne/Crédit à Base Communautaire (P.E.B.Co) a été ôtée du Département Communautaire et Assainissement du Milieu (DCAM) et érigée en département de micro finance à part entière.
            Toujours dans le souci de se conformer aux réglementations en vigueur en ce qui concerne les systèmes financiers décentralisés, le Conseil d'Administration de l'ONG BETHESDA a concédé une autonomie de gestion à l'Association P.E.B.Co-BETHESDA en le dotant d'une direction générale hiérarchiquement dépendante du Conseil d'Administration de P.E.B.Co-BETHESDA et de nouveaux textes intitulés << Règlements et Statuts des Systèmes Financiers Décentralisés >>. L'Association P.E.B.Co-BETHESDA a en effet, acquis depuis son Assemblée Générale Constitutive du 11 mai 2013, son statut juridique à part entière, se conformant ainsi à la Nouvelle Loi N°2012-14 du 21 mars 2012 portant réglementation des Systèmes Financiers Décentralisés en République du Bénin. Elle n'est plus un département de l'ONG BETHESDA et est une structure totalement indépendante dans le fonctionnement comme dans l'organisation.",
               'location' => 'Cotonou',
               'image' => 'news_images/1KwlfUUcHhzHx6MzivnrUTvOhNtDUPUoBKqmVsZB.jpg'
          ];
          NewsArticle::insert([
               $article1,
               $article2,
          ]);
     }
}
